module.exports = {
  TELEGRAM_TOKEN: process.env.TELEGRAM_TOKEN,
  SUBSCAN_API_KEY: process.env.SUBSCAN_API_KEY,
  SUBSCAN_API_DELAY: process.env.SUBSCAN_API_DELAY,
  DEFAULT_STASH: process.env.DEFAULT_STASH,
}